image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - yarn  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

test_script:
  - yarn lint && yarn test  # скрипт тестирования

deploy_script:  # скрипт развёртывания
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - git config --global user.name "TatianaLevoshko"
  - git config --global user.email "delovoiy86@gmail.com"
  - npx gh-pages -d dist -u "TatianaLevoshko <delovoiy86@gmail.com>"

